# Generated by Django 5.0.2 on 2024-03-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0003_imageelement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageelement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mediaphoto'),
        ),
    ]
