# Generated by Django 5.0.2 on 2024-03-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0004_alter_imageelement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageelement',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='imageelement',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imageelement',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
